#
# starship
# 0.36.0
# https://github.com/starship/starship
#

# Don't print a new line at the start of the prompt
#add_newline = false
add_newline = true

[directory]
truncate_to_repo = true

[character]
symbol = "❯"

[cmd_duration]
prefix = ""
min_time = 5

[battery]
disabled = true

[golang]
disabled = true

[hostname]
# Hide hostname unless accessing via SSH
ssh_only = true

[jobs]
disabled = true

[nix_shell]
disabled = true

# Shows used NodeJS version
[nodejs]
symbol = "■ "

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

